#import libraries

In [2]:
import pandas as pd
import numpy as np
import os

#import pickle & csv for merge

In [3]:
path='/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data/df_merged_large.pkl'

In [8]:
df_orders_products_combined=pd.read_pickle(os.path.join(path))

In [25]:
#Check shape of imported data

In [9]:
df_orders_products_combined.shape

(32434489, 11)

In [26]:
#Repeat procedure

In [13]:
path='/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data/df_prods_clean_no_dups.csv'

In [15]:
df_prods=pd.read_csv(os.path.join(path),index_col=False)

In [16]:
df_prods.shape

(49672, 6)

In [27]:
#check for shared column to merge on

In [17]:
df_prods.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices
0,0,1,Chocolate Sandwich Cookies,61,19,5.8
1,1,2,All-Seasons Salt,104,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,4,5,Green Chile Anytime Sauce,5,13,4.3

In [18]:
df_orders_products_combined.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,0,2539329,1,1,2,8,NaN,196,1,0,both
1,0,2539329,1,1,2,8,NaN,14084,2,0,both
2,0,2539329,1,1,2,8,NaN,12427,3,0,both
3,0,2539329,1,1,2,8,NaN,26088,4,0,both
4,0,2539329,1,1,2,8,NaN,26405,5,0,both

In [28]:
#merge dfs

In [22]:
df_ords_prods_merge = df_orders_products_combined.merge(df_prods, on='product_id', indicator='merge_indicator')

Checking if the merge worked
head to see if the indicator column checks out
and value_counts()for consistency of the merge

In [30]:
df_ords_prods_merge.head()

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,merge_indicator
0,0,2539329,1,1,2,8,NaN,196,1,0,both,195,Soda,77,7,9.0,both
1,0,2539329,1,1,2,8,NaN,14084,2,0,both,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,0,2539329,1,1,2,8,NaN,12427,3,0,both,12427,Original Beef Jerky,23,19,4.4,both
3,0,2539329,1,1,2,8,NaN,26088,4,0,both,26089,Aged White Cheddar Popcorn,23,19,4.7,both
4,0,2539329,1,1,2,8,NaN,26405,5,0,both,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

In [31]:
df_ords_prods_merge['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [29]:
#export merged df as pickle (because of its size)

In [24]:
df_ords_prods_merge.to_pickle(os.path.join(path,'/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data/df_ords_prods_merge.pkl'))

In [ ]:
#for several days my computer couldn't handle the data , I tried but it crashed. Thankfully for whatever reason it worked now.