In [2]:
#Import Libraries
import pandas as pd
import numpy as np
import os

In [3]:
path='/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv'

In [6]:
df_prior=pd.read_csv(os.path.join(path),index_col=False)

In [7]:
path='/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data/orders.csv'

In [8]:
df_ords=pd.read_csv(os.path.join(path),index_col=False)

In [10]:
df_prior.shape

(32434489, 4)

In [11]:
df_ords.shape

(3421083, 7)

In [12]:
path='/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data/df_ords_w_clean.csv'

In [13]:
df_ords_clean=pd.read_csv(os.path.join(path),index_col=False)

In [14]:
df_ords_clean.shape

(49672, 6)

In [15]:
df_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [16]:
df_ords.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order
0,0,2539329,1,1,2,8,NaN
1,1,2398795,1,2,3,7,15.0
2,2,473747,1,3,3,12,21.0
3,3,2254736,1,4,4,7,29.0
4,4,431534,1,5,4,15,28.0

In [24]:
df_merged_large = df_ords.merge(df_prior, on = 'order_id', indicator = True)
#merging both df on order_id column

In [19]:
df_merged_large.shape

(32434489, 11)

In [20]:
df_merged_large.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,0,2539329,1,1,2,8,NaN,196,1,0,both
1,0,2539329,1,1,2,8,NaN,14084,2,0,both
2,0,2539329,1,1,2,8,NaN,12427,3,0,both
3,0,2539329,1,1,2,8,NaN,26088,4,0,both
4,0,2539329,1,1,2,8,NaN,26405,5,0,both

In [26]:
df_merged_large['_merge'].value_counts()
#checking the merge
# can not us normal parentheses for the code to work for checking the full merge, alternative?

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [31]:
df_merged_large.to_pickle(os.path.join('/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data', 'df_merged_large.pkl'))